apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor
  namespace: dqn-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actor
  template:
    metadata:
      labels:
        app: actor
    spec:
      containers:
      - name: actor
        image: guswong/atari-actor:latest
        command: ["/bin/bash", "-c"]
        args:
        - "until nc -z redis 6379; do echo 'Waiting for Redis...'; sleep 10; done; python actor.py"