apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: dqn-training
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        args: ["redis-server", "--maxmemory", "4gb", "--maxmemory-policy", "allkeys-lru"]
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "4.5Gi"
          requests:
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dqn-training
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379